package interfaz.grafica;

import com.mycompany.transacciones.DataBase;
import java.awt.Frame;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dgc06
 */
public class TablaIU extends javax.swing.JFrame {

    /**
     * Creates new form TablaIU
     *
     * @throws java.sql.SQLException
     */
    DataBase db;
    DefaultTableModel model;
    String sql, filtroConsulta = "";
    boolean ordAscLegajo = true;
    boolean ordAscCant = true;
    boolean ordAscImporte = true;

    public TablaIU(DataBase db) throws SQLException {
        this.db = db;
        initComponents();
       // configTable();

        sql = "SELECT * FROM (SELECT g.grupo, g.empresa, tipo_doc, nro_doc, secuencia, "
                + "cod_concepto, descrip_concepto, cantidad, importe, "
                + "fechaDate AS fecha_aplicacion, fechaString AS fecha_csv "
                + "FROM transaccion t "
                + "LEFT JOIN grupo_empresa g "
                + "ON t.id_grup_emp = g.id_grup_emp) AS t";
        jTable1.setModel(crearModel(db.consulta(sql)));

        cargarImagenes();
        alinearColumnas();
        generarTotales(filtroConsulta);
        cargarFechas();
        configurarElemtosSwing();
    }

    private DefaultTableModel crearModel(ResultSet rs) throws SQLException {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        boolean columnasNoCargadas = true;
        int indexFila;
        String resultadoSQL = "";
        int numColumnas = 0;

        try {
            numColumnas = rs.getMetaData().getColumnCount();

            while (rs.next()) {
                if (columnasNoCargadas) {
                    for (int i = 1; i <= numColumnas; i++) {
                        if (!"".equals(resultadoSQL)) {
                            if (i < numColumnas) {
                                resultadoSQL = rs.getMetaData().getColumnName(i);
                            } else {
                                resultadoSQL = rs.getMetaData().getColumnName(i) + resultadoSQL;
                            }
                        } else if (i < numColumnas) {
                            resultadoSQL = rs.getMetaData().getColumnName(i);
                        } else {
                            resultadoSQL = rs.getMetaData().getColumnName(i);
                        }

                        model.addColumn(resultadoSQL);
                        resultadoSQL = "";
                        columnasNoCargadas = false;
                    }
                }
                Object[] row = new Object[numColumnas];
                indexFila = 0;
                Object obj;
                resultadoSQL = " ";

                for (int i = 1; i <= numColumnas; i++) {
                    obj = rs.getObject(i);
                    if (obj != null) {
                        if (obj instanceof Double) {
                            DecimalFormat formatea = new DecimalFormat("###,##0.00");
                            row[indexFila] = formatea.format(obj);
                        } else {
                            row[indexFila] = "SADSd";
                        }
                        indexFila++;

                        resultadoSQL = "";
                    }
                }
                model.addRow(row);

                resultadoSQL = "";

            }
        } catch (SQLException e) {
        }
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        grupoCheck = new javax.swing.JCheckBox();
        descripcionCheck = new javax.swing.JCheckBox();
        javax.swing.JButton filtrarBtn = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        exportarBtn = new javax.swing.JButton();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        descripcionTextField = new javax.swing.JTextField();
        empresajField = new javax.swing.JTextField();
        empresaCheck = new javax.swing.JCheckBox();
        totalImporte = new javax.swing.JLabel();
        totalReg1 = new javax.swing.JLabel();
        totalLegajos = new javax.swing.JLabel();
        totalDoc = new javax.swing.JLabel();
        docField = new javax.swing.JTextField();
        documentoCheck = new javax.swing.JCheckBox();
        grupojField1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        legajoField = new javax.swing.JTextField();
        jLabel10CD = new javax.swing.JLabel();
        legajoCheck = new javax.swing.JCheckBox();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        conceptoCheck = new javax.swing.JCheckBox();
        conceptoTextField = new javax.swing.JTextField();
        FechaCheck = new javax.swing.JCheckBox();
        ordImporte = new javax.swing.JLabel();
        ordCant = new javax.swing.JLabel();
        ordLejago = new javax.swing.JLabel();
        FechaComboBox = new javax.swing.JComboBox<>();
        conceptoDistintoCheck1 = new javax.swing.JCheckBox();
        jLabel13CD = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel14CD = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("distintos");

        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setEditingColumn(0);
        jTable1.setEditingRow(0);
        jScrollPane1.setViewportView(jTable1);

        grupoCheck.setBackground(new java.awt.Color(255, 255, 255));
        grupoCheck.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        grupoCheck.setForeground(new java.awt.Color(51, 51, 51));
        grupoCheck.setText("Grupo");
        grupoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoCheckActionPerformed(evt);
            }
        });

        descripcionCheck.setBackground(new java.awt.Color(255, 255, 255));
        descripcionCheck.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        descripcionCheck.setForeground(new java.awt.Color(51, 51, 51));
        descripcionCheck.setText("Descripcion");
        descripcionCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionCheckActionPerformed(evt);
            }
        });

        filtrarBtn.setBackground(new java.awt.Color(0, 153, 102));
        filtrarBtn.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        filtrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        filtrarBtn.setText("Filtrar");
        filtrarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        filtrarBtn.setBorderPainted(false);
        filtrarBtn.setFocusable(false);
        filtrarBtn.setRequestFocusEnabled(false);
        filtrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filtrarBtnMouseClicked(evt);
            }
        });
        filtrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("CONTROL DE TRANSACCIONES");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("N°");

        exportarBtn.setBackground(new java.awt.Color(0, 153, 102));
        exportarBtn.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        exportarBtn.setForeground(new java.awt.Color(255, 255, 255));
        exportarBtn.setText("Exportar");
        exportarBtn.setToolTipText("");
        exportarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exportarBtn.setBorderPainted(false);
        exportarBtn.setFocusPainted(false);
        exportarBtn.setFocusable(false);
        exportarBtn.setRequestFocusEnabled(false);
        exportarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarBtnActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Importe Total:");
        jLabel3.setVerifyInputWhenFocusTarget(false);

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Total Registros:");
        jLabel6.setVerifyInputWhenFocusTarget(false);

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("distintos");
        jLabel8.setVerifyInputWhenFocusTarget(false);

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Total Documentos:");
        jLabel9.setVerifyInputWhenFocusTarget(false);

        descripcionTextField.setEnabled(false);
        descripcionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionTextFieldActionPerformed(evt);
            }
        });
        descripcionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripcionTextFieldKeyTyped(evt);
            }
        });

        empresajField.setEnabled(false);
        empresajField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresajFieldActionPerformed(evt);
            }
        });
        empresajField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empresajFieldKeyTyped(evt);
            }
        });

        empresaCheck.setBackground(new java.awt.Color(255, 255, 255));
        empresaCheck.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        empresaCheck.setForeground(new java.awt.Color(51, 51, 51));
        empresaCheck.setText("Empresa");
        empresaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaCheckActionPerformed(evt);
            }
        });

        totalImporte.setText("--------");

        totalReg1.setText("--------");

        totalLegajos.setText("--------");

        totalDoc.setText("--------");

        docField.setEnabled(false);
        docField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docFieldActionPerformed(evt);
            }
        });
        docField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                docFieldKeyTyped(evt);
            }
        });

        documentoCheck.setBackground(new java.awt.Color(255, 255, 255));
        documentoCheck.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        documentoCheck.setForeground(new java.awt.Color(51, 51, 51));
        documentoCheck.setText("Documento");
        documentoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoCheckActionPerformed(evt);
            }
        });

        grupojField1.setEnabled(false);
        grupojField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupojField1ActionPerformed(evt);
            }
        });
        grupojField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                grupojField1KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("FILTROS");

        legajoField.setEnabled(false);
        legajoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legajoFieldActionPerformed(evt);
            }
        });
        legajoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                legajoFieldKeyTyped(evt);
            }
        });

        jLabel10CD.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel10CD.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10CD.setText("N°");
        jLabel10CD.setEnabled(false);

        legajoCheck.setBackground(new java.awt.Color(255, 255, 255));
        legajoCheck.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        legajoCheck.setForeground(new java.awt.Color(51, 51, 51));
        legajoCheck.setText("Legajo");
        legajoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legajoCheckActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Total Legajos:");
        jLabel11.setVerifyInputWhenFocusTarget(false);

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("distintos");
        jLabel12.setVerifyInputWhenFocusTarget(false);

        conceptoCheck.setBackground(new java.awt.Color(255, 255, 255));
        conceptoCheck.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        conceptoCheck.setForeground(new java.awt.Color(51, 51, 51));
        conceptoCheck.setText("Cod concepto");
        conceptoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conceptoCheckActionPerformed(evt);
            }
        });

        conceptoTextField.setEnabled(false);
        conceptoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conceptoTextFieldActionPerformed(evt);
            }
        });
        conceptoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                conceptoTextFieldKeyTyped(evt);
            }
        });

        FechaCheck.setBackground(new java.awt.Color(255, 255, 255));
        FechaCheck.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        FechaCheck.setForeground(new java.awt.Color(51, 51, 51));
        FechaCheck.setText("Fecha. A");
        FechaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaCheckActionPerformed(evt);
            }
        });

        ordImporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ordImporte.setForeground(new java.awt.Color(51, 51, 51));
        ordImporte.setText("Ord. Importe");
        ordImporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordImporteMouseClicked(evt);
            }
        });

        ordCant.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ordCant.setForeground(new java.awt.Color(51, 51, 51));
        ordCant.setText("Ord. Cantidad");
        ordCant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordCantMouseClicked(evt);
            }
        });

        ordLejago.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ordLejago.setForeground(new java.awt.Color(51, 51, 51));
        ordLejago.setText("Ord. Legajo");
        ordLejago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordLejagoMouseClicked(evt);
            }
        });

        FechaComboBox.setEnabled(false);
        FechaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaComboBoxActionPerformed(evt);
            }
        });

        conceptoDistintoCheck1.setBackground(new java.awt.Color(255, 255, 255));
        conceptoDistintoCheck1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        conceptoDistintoCheck1.setForeground(new java.awt.Color(51, 51, 51));
        conceptoDistintoCheck1.setText("conceptos");
        conceptoDistintoCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conceptoDistintoCheck1ActionPerformed(evt);
            }
        });

        jLabel13CD.setFont(new java.awt.Font("Roboto Medium", 0, 11)); // NOI18N
        jLabel13CD.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13CD.setText("Descripcion");
        jLabel13CD.setEnabled(false);

        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner1.setEnabled(false);

        jLabel14CD.setFont(new java.awt.Font("Roboto Medium", 0, 11)); // NOI18N
        jLabel14CD.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14CD.setText("Caracteres");
        jLabel14CD.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("N°");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grupoCheck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(grupojField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(empresaCheck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(empresajField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(documentoCheck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(docField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(legajoCheck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(7, 7, 7)
                        .addComponent(legajoField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(descripcionCheck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(descripcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(conceptoCheck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(conceptoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(conceptoDistintoCheck1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10CD)
                            .addComponent(jLabel13CD)
                            .addComponent(jLabel14CD))
                        .addGap(3, 3, 3)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaCheck)
                    .addComponent(FechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(filtrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(totalReg1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12)))
                        .addGap(4, 4, 4)
                        .addComponent(totalLegajos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel8)))
                        .addGap(7, 7, 7)
                        .addComponent(totalDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(totalImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addComponent(exportarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(460, 460, 460)
                                .addComponent(ordLejago, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(ordImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(ordCant, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ordLejago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordCant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(grupoCheck)
                        .addGap(6, 6, 6)
                        .addComponent(grupojField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(empresaCheck)
                        .addGap(6, 6, 6)
                        .addComponent(empresajField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(documentoCheck)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(legajoCheck)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(legajoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(descripcionCheck)
                        .addGap(6, 6, 6)
                        .addComponent(descripcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(conceptoCheck)
                        .addGap(6, 6, 6)
                        .addComponent(conceptoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(conceptoDistintoCheck1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10CD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel13CD))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel14CD))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(FechaCheck)
                        .addGap(4, 4, 4)
                        .addComponent(FechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(filtrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(totalReg1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12))
                    .addComponent(totalLegajos)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(totalDoc)
                    .addComponent(jLabel3)
                    .addComponent(totalImporte))
                .addGap(10, 10, 10)
                .addComponent(exportarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        totalImporte.getAccessibleContext().setAccessibleName("totalRegistros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void filtrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrarBtnActionPerformed

    private void grupoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoCheckActionPerformed
        // TODO add your handling code here:
        if (grupoCheck.isSelected()) {
            grupojField1.setEnabled(true);
        } else {
            grupojField1.setEnabled(false);
        }

    }//GEN-LAST:event_grupoCheckActionPerformed

    private void descripcionCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionCheckActionPerformed

        if (descripcionCheck.isSelected()) {
            descripcionTextField.setEnabled(true);
        } else {
            descripcionTextField.setEnabled(false);
        }
    }//GEN-LAST:event_descripcionCheckActionPerformed

    private void filtrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtrarBtnMouseClicked

        filtroConsulta = "SELECT * FROM (SELECT g.grupo, g.empresa, tipo_doc, nro_doc, secuencia, "
                + "cod_concepto, descrip_concepto, cantidad, importe, "
                + "fechaDate AS fecha_aplicacion, fechaString AS fecha_csv "
                + "FROM transaccion t "
                + "LEFT JOIN grupo_empresa g "
                + "ON t.id_grup_emp = g.id_grup_emp) AS t";

        String atributoSql = "";
        Statement stmt = null;

        if (grupoCheck.isSelected() && !grupojField1.getText().isEmpty()) {
            atributoSql = " WHERE " + "t.grupo = '" + limpiarCadena(grupojField1.getText()) + "'";
//            atributoSql = " WHERE " + "t.grupo = '" + grupojField1.getText().replace(" ", "").toUpperCase() + "'";
        }

        if (empresaCheck.isSelected() && !empresajField.getText().isEmpty()) {
            if (!"".equals(atributoSql)) {
                atributoSql += " AND t.empresa = '" + limpiarCadena(empresajField.getText()) + "'";
            } else {
                atributoSql = " WHERE " + "t.empresa = '" + limpiarCadena(empresajField.getText()) + "'";
            }
        }

        if (documentoCheck.isSelected() && !docField.getText().isEmpty()) {
            if (!"".equals(atributoSql)) {
                atributoSql += " AND t.nro_doc like '" + docField.getText() + "%'";
//                atributoSql += " AND t.nro_doc = '" + docField.getText() + "'";
            } else {
                atributoSql = " WHERE " + "t.nro_doc like '" + docField.getText() + "%'";
//                atributoSql = " WHERE " + "t.nro_doc = '" + docField.getText() + "'";
            }
        }

        if (legajoCheck.isSelected() && !legajoField.getText().isEmpty()) {
            if (!"".equals(atributoSql)) {
                //Lo que hace la consulta es concatenar las columnas y compara con un like + valor ingresado por el usuario
                atributoSql += " AND (t.tipo_doc || t.nro_doc || t.secuencia) like '" + limpiarCadena(legajoField.getText()) + "%'";
            } else {
                atributoSql = " WHERE (t.tipo_doc || t.nro_doc || t.secuencia) like '" + limpiarCadena(legajoField.getText()) + "%'";
            }
        }

        if (descripcionCheck.isSelected() && !descripcionTextField.getText().isEmpty()) {
            if (!"".equals(atributoSql)) {
                atributoSql += " AND descrip_concepto like '%" + descripcionTextField.getText() + "%'";
            } else {
                atributoSql = " WHERE " + "descrip_concepto like '%" + descripcionTextField.getText() + "%'";
            }
        }

        if (conceptoCheck.isSelected() && !conceptoTextField.getText().isEmpty()) {
            if (!"".equals(atributoSql)) {
                atributoSql += " AND t.cod_concepto = '" + conceptoTextField.getText() + "'";
            } else {
                atributoSql = " WHERE t.cod_concepto = '" + conceptoTextField.getText() + "'";
            }
        }

        if (FechaCheck.isSelected()) {
            if (!"".equals(atributoSql)) {
                atributoSql += " AND t.fecha_aplicacion = '" + FechaComboBox.getSelectedItem().toString() + "'";

            } else {
                atributoSql = " WHERE t.fecha_aplicacion = '" + FechaComboBox.getSelectedItem().toString() + "'";
            }
        }

        if (conceptoDistintoCheck1.isSelected() && !jSpinner1.getValue().toString().isEmpty()) {
            filtroConsulta = "    SELECT  DISTINCT g.grupo, g.empresa, cod_concepto, substr(descrip_concepto,1," + jSpinner1.getValue().toString() + ") as descripcion \n"
                    + "    FROM transaccion t\n"
                    + "    LEFT JOIN grupo_empresa g\n"
                    + "    ON t.id_grup_emp = g.id_grup_emp\n"
                    + "	ORDER BY 2, 3";
        }

        filtroConsulta += atributoSql;

        if (!"".equals(filtroConsulta)) {
            try {
                System.out.println(filtroConsulta);
                jTable1.setModel(crearModel(db.consulta(filtroConsulta)));

                if (!tablaVacia()) {
                    if (!conceptoDistintoCheck1.isSelected()) {
                        generarTotales(filtroConsulta);
                        alinearColumnas();
                    } else {
                        limpiarTotales();
                    }
                }
                //habiltia boton exportar
                exportarBtn.setEnabled(true);
                // redimensionar();
                /*jTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(100);
                 */
            } catch (SQLException ex) {
                Logger.getLogger(TablaIU.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_filtrarBtnMouseClicked

    //limpia el String eliminando espacios vacios y letras en minuscula
    private String limpiarCadena(String cadena) {
        return cadena.toUpperCase().replace(" ", "");
    }

    private void redimensionar() {
        int maxColum;
        if (grupoCheck.isSelected()) {
            maxColum = 10;

            int i = 0;
            while (i <= maxColum) {
                if (i >= 8) {
                    jTable1.getColumnModel().getColumn(i).setPreferredWidth(100);
                } else {
                    jTable1.getColumnModel().getColumn(i).setPreferredWidth(30);
                }
                i++;
            }
        }

        if (descripcionCheck.isSelected()) {
            maxColum = 11;

            int i = 0;
            while (i <= maxColum) {
                if (i >= 9) {
                    jTable1.getColumnModel().getColumn(i).setPreferredWidth(100);
                } else {
                    jTable1.getColumnModel().getColumn(i).setPreferredWidth(30);
                }
                i++;
            }
        }
    }

    private void generarTotales(String filtroConsulta1) {
        // Si mi numero total de registros es 0, entonces 
        //no tiene sentido que verifique el resto

        String totalRegistro = obtenerTotalRegistro();

        totalReg1.setText(totalRegistro);

        if (!"0".equals(totalRegistro)) {
            try {
                totalLegajos.setText(obtenerTotalLegajos());
                totalDoc.setText(obtenerTotalDocumentos());
                totalImporte.setText(obtenerTotalImporte());
            } catch (NullPointerException e) {
            }
        } else {
            //Se pone un 0 directamente
            totalLegajos.setText("0");
            totalDoc.setText("0");
            totalImporte.setText("0");
        }
    }

    private void exportarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        fileChooser.setDialogTitle("Guardar");

        FileFilter csvFilter = new FileNameExtensionFilter("Archivos de CSV", "csv", "csv");
        fileChooser.addChoosableFileFilter(csvFilter);

        // Deshabilita la opción "Todos los archivos"
        fileChooser.setAcceptAllFileFilterUsed(false);

        File archivo = new File("");
        fileChooser.setSelectedFile(archivo);

        int resultado = fileChooser.showDialog(null, "Guardar");

        if (resultado == JFileChooser.APPROVE_OPTION) {

            archivo = fileChooser.getSelectedFile();
            String nombreArchivo = archivo.getName();
            if (!nombreArchivo.toLowerCase().endsWith(".csv")) {
                archivo = new File(archivo.getParentFile(), nombreArchivo + ".csv");
            }

//            String nombreArchivoPredeterminado = "[REP]";
//            int maxLength = 15;
//
//            if (nombreArchivo.length() > maxLength) {
//                nombreArchivo = nombreArchivo.substring(0, maxLength);
//            }
            if (archivo.exists()) {

                int opcion = JOptionPane.showConfirmDialog(null, "El archivo ya existe. ¿Desea reemplazarlo?", "Confirmar reemplazo", JOptionPane.YES_NO_OPTION);

                if (opcion == JOptionPane.YES_OPTION) {
                    try {
                        this.db.exportarCSV(archivo, sql, nombreArchivo);
                    } catch (Exception ex) {
                        Logger.getLogger(TablaIU.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                try {
                    this.db.exportarCSV(archivo, sql, nombreArchivo);
                } catch (Exception ex) {
                    Logger.getLogger(TablaIU.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_exportarBtnActionPerformed

    private void subParcialCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subParcialCheckActionPerformed
    }//GEN-LAST:event_subParcialCheckActionPerformed

    private void descripcionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionTextFieldActionPerformed

    private void descripcionTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionTextFieldKeyTyped

    private void empresajFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresajFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_empresajFieldActionPerformed

    private void empresajFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empresajFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_empresajFieldKeyTyped

    /**
     * Alineamos las columnas a nuestra conveniencia
     */
    private void alinearColumnas() {
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
//        jTable1.getColumnModel().getColumn(8).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(7).setCellRenderer(cellRenderer);
        jTable1.getColumnModel().getColumn(8).setCellRenderer(cellRenderer);
    }

    private void empresaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaCheckActionPerformed
        // TODO add your handling code here:
        if (empresaCheck.isSelected()) {
            empresajField.setEnabled(true);
        } else {
            empresajField.setEnabled(false);
        }
    }//GEN-LAST:event_empresaCheckActionPerformed

    private void docFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docFieldActionPerformed

    private void docFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docFieldKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar(); // Recogemos, a partir del evento, la tecla que se pulsó
        int limite = 8;
        if (!Character.isDigit(teclaPulsada)) { // Si la tecla pulsada no es un dígito, entonces...
            evt.consume(); // Borramos la última letra introducida (lo hace muy rápido, la
            // letra nunca se escribe en el textfield)
        }
        if (docField.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_docFieldKeyTyped

    private void documentoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoCheckActionPerformed
        // TODO add your handling code here:

        if (documentoCheck.isSelected()) {
            docField.setEnabled(true);
            legajoCheck.setSelected(false);
            legajoCheck.setEnabled(false);
            legajoField.setEnabled(false);
        } else {
            docField.setEnabled(false);
            legajoCheck.setEnabled(true);
        }
    }//GEN-LAST:event_documentoCheckActionPerformed

    private void grupojField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupojField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupojField1ActionPerformed

    private void grupojField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grupojField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_grupojField1KeyTyped

    private void legajoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legajoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_legajoFieldActionPerformed

    private void legajoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_legajoFieldKeyTyped
        // TODO add your handling code here:
        int limite = 13;
        char teclaPulsada = evt.getKeyChar(); // Recogemos, a partir del evento, la tecla que se pulsó
        if (!Character.isDigit(teclaPulsada)) { // Si la tecla pulsada no es un dígito, entonces...
            evt.consume(); // Borramos la última letra introducida (lo hace muy rápido, la
            // letra nunca se escribe en el textfield)
        }
        if (legajoField.getText().length() == limite) {
            evt.consume();
        }
    }//GEN-LAST:event_legajoFieldKeyTyped

    private void legajoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legajoCheckActionPerformed
        // TODO add your handling code here:
        if (legajoCheck.isSelected()) {
            legajoField.setEnabled(true);
            documentoCheck.setSelected(false);
            documentoCheck.setEnabled(false);
            docField.setEnabled(false);
        } else {
            documentoCheck.setEnabled(true);
            legajoField.setEnabled(false);
        }
    }//GEN-LAST:event_legajoCheckActionPerformed

    private void conceptoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conceptoCheckActionPerformed
        // TODO add your handling code here:
        if (conceptoCheck.isSelected()) {
            conceptoTextField.setEnabled(true);
        } else {
            conceptoTextField.setEnabled(false);
        }

    }//GEN-LAST:event_conceptoCheckActionPerformed

    private void conceptoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conceptoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conceptoTextFieldActionPerformed

    private void conceptoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conceptoTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_conceptoTextFieldKeyTyped

    private void FechaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaCheckActionPerformed
        // TODO add your handling code here:
        if (FechaCheck.isSelected()) {
            FechaComboBox.setEnabled(true);
        } else {
            FechaComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_FechaCheckActionPerformed

    private void ordLejagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordLejagoMouseClicked

        if (!conceptoDistintoCheck1.isSelected()) {
            String consultaOrd;
            try {
                // TODO add your handling code here:
                if (ordAscLegajo) {
                    if (filtroConsulta.isEmpty()) {
                        consultaOrd = sql + " ORDER BY tipo_doc || nro_doc || secuencia ASC";

                    } else {
                        consultaOrd = filtroConsulta + " ORDER BY t.tipo_doc || t.nro_doc || t.secuencia ASC";

                    }
                    ordAscLegajo = false;
                    //! ME PEDIA UN MERGE ASI QUE COMENTE PORQUE NO SABIA QUE VA
//                sql = filtroConsulta;
//                " ORDER BY t.tipo_doc , t.nro_doc , t.secuencia ASC";
                } else {
                    if (filtroConsulta.isEmpty()) {
                        consultaOrd = sql + " ORDER BY tipo_doc || nro_doc || secuencia DESC";

                    } else {
                        consultaOrd = filtroConsulta + " ORDER BY t.tipo_doc || t.nro_doc || t.secuencia DESC";
                    }
                    ordAscLegajo = true;
                }

                jTable1.setModel(crearModel(db.consulta(consultaOrd)));
                alinearColumnas();
            } catch (SQLException ex) {
                Logger.getLogger(TablaIU.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_ordLejagoMouseClicked

    private void FechaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaComboBoxActionPerformed

    private void conceptoDistintoCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conceptoDistintoCheck1ActionPerformed
        // TODO add your handling code here:
        if (conceptoDistintoCheck1.isSelected()) {
            jLabel10CD.setEnabled(true);
            jLabel13CD.setEnabled(true);
            jLabel14CD.setEnabled(true);
            jSpinner1.setEnabled(true);
            grupoCheck.setEnabled(false);
            grupoCheck.setSelected(false);
            empresaCheck.setEnabled(false);
            empresaCheck.setSelected(false);
            documentoCheck.setEnabled(false);
            documentoCheck.setSelected(false);
            descripcionCheck.setEnabled(false);
            descripcionCheck.setSelected(false);
            conceptoCheck.setEnabled(false);
            conceptoCheck.setSelected(false);
            FechaCheck.setEnabled(false);
            FechaCheck.setSelected(false);
            legajoCheck.setEnabled(false);
            legajoCheck.setSelected(false);
            grupojField1.setEnabled(false);
            empresajField.setEnabled(false);
            docField.setEnabled(false);
            descripcionTextField.setEnabled(false);
            conceptoTextField.setEnabled(false);
            FechaComboBox.setEnabled(false);
            legajoField.setEnabled(false);

        } else {
            jLabel10CD.setEnabled(false);
            jLabel13CD.setEnabled(false);
            jLabel14CD.setEnabled(false);
            jSpinner1.setEnabled(false);
            grupoCheck.setEnabled(true);
            empresaCheck.setEnabled(true);
            documentoCheck.setEnabled(true);
            descripcionCheck.setEnabled(true);
            conceptoCheck.setEnabled(true);
            FechaCheck.setEnabled(true);
            legajoCheck.setEnabled(true);
        }
    }//GEN-LAST:event_conceptoDistintoCheck1ActionPerformed

    private void ordImporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordImporteMouseClicked
        if (!conceptoDistintoCheck1.isSelected()) {
            String consultaOrd;
            try {
                // TODO add your handling code here:
                if (ordAscImporte) {
                    if (filtroConsulta.isEmpty()) {
                        consultaOrd = sql + " ORDER BY t.importe ASC";

                    } else {
                        consultaOrd = filtroConsulta + " ORDER BY t.importe ASC";
                    }
                    ordAscImporte = false;
                    //! ME PEDIA UN MERGE ASI QUE COMENTE PORQUE NO SABIA QUE VA
//                sql = filtroConsulta;
//                " ORDER BY t.tipo_doc , t.nro_doc , t.secuencia ASC";
                } else {
                    if (filtroConsulta.isEmpty()) {
                        consultaOrd = sql + " ORDER BY t.importe DESC";

                    } else {
                        consultaOrd = filtroConsulta + " ORDER BY t.importe DESC";
                    }
                    ordAscImporte = true;
                }
                jTable1.setModel(crearModel(db.consulta(consultaOrd)));
                alinearColumnas();
            } catch (SQLException ex) {

                Logger.getLogger(TablaIU.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ordImporteMouseClicked

    private void ordCantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordCantMouseClicked
        // TODO add your handling code here:
        if (!conceptoDistintoCheck1.isSelected()) {
            String consultaOrd;
            try {
                // TODO add your handling code here:
                if (ordAscCant) {
                    if (filtroConsulta.isEmpty()) {
                        consultaOrd = sql + " ORDER BY t.cantidad ASC";
                    } else {
                        consultaOrd = filtroConsulta + " ORDER BY t.cantidad ASC";
                    }
                    ordAscCant = false;
                    //! ME PEDIA UN MERGE ASI QUE COMENTE PORQUE NO SABIA QUE VA
//                sql = filtroConsulta;
//                " ORDER BY t.tipo_doc , t.nro_doc , t.secuencia ASC";
                } else {
                    if (filtroConsulta.isEmpty()) {
                        consultaOrd = sql + " ORDER BY t.cantidad DESC";

                    } else {
                        consultaOrd = filtroConsulta + " ORDER BY t.cantidad DESC";
                    }
                    ordAscCant = true;
                }
                jTable1.setModel(crearModel(db.consulta(consultaOrd)));
                alinearColumnas();
            } catch (SQLException ex) {

                Logger.getLogger(TablaIU.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ordCantMouseClicked

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
         if (evt.equals(Frame.MAXIMIZED_BOTH)) {
                // Si se maximiza, ajusta el JFrame al tamaño de la pantalla
                this.setExtendedState(Frame.NORMAL);
                this.setExtendedState(Frame.MAXIMIZED_BOTH);
            }
    }//GEN-LAST:event_formComponentResized

    private String obtenerTotalRegistro() {

        try {
            String condicion = "count(*)";
            String consultaSQL;
            if ("".equals(filtroConsulta)) {
                consultaSQL = "SELECT " + condicion + " as total FROM (" + sql + ") as l";
            } else {
                consultaSQL = "SELECT " + condicion + " as total FROM (" + filtroConsulta + ") as l";
            }
            ResultSet resultSet = db.consulta(consultaSQL);
            return resultSet.getString(1);
        } catch (SQLException ex) {
            Logger.getLogger(TablaIU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        return "-1";
    }

    private String obtenerTotalLegajos() {

        try {
            String condicion = "count(DISTINCT l.tipo_doc || l.nro_doc || l.secuencia)";

            String consultaSQL;

            if ("".equals(filtroConsulta)) {
                consultaSQL = "SELECT " + condicion + " as total FROM (" + sql + ") as l";
            } else {
                consultaSQL = "SELECT " + condicion + " as total FROM (" + filtroConsulta + ") as l";
            }
            ResultSet resultSet = db.consulta(consultaSQL);
            return resultSet.getString(1);

        } catch (SQLException ex) {
            Logger.getLogger(TablaIU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        return "-1";
    }

    private String obtenerTotalDocumentos() {
        try {
            String condicion = "count(DISTINCT l.nro_doc)";
            String consultaSQL;

            if ("".equals(filtroConsulta)) {
                consultaSQL = "SELECT " + condicion + " as total FROM (" + sql + ") as l";
            } else {
                consultaSQL = "SELECT " + condicion + " as total FROM (" + filtroConsulta + ") as l";
            }
            ResultSet resultSet = db.consulta(consultaSQL);
            return resultSet.getString(1);

        } catch (SQLException ex) {
            Logger.getLogger(TablaIU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        return "-1";
    }

    private String obtenerTotalImporte() {

        //no se puede usar SUM(l.importe) ya que solo suma los valores enteros solamente
        String condicion = "l.importe";

        try {
            String consultaSQL;
            if ("".equals(filtroConsulta)) {
                consultaSQL = "SELECT " + condicion + " as total FROM (" + sql + ") as l";
            } else {
                consultaSQL = "SELECT " + condicion + " as total FROM (" + filtroConsulta + ") as l";
            }
            ResultSet resultSet = db.consulta(consultaSQL);
            double importe = procesarValoresImportes(resultSet);
            DecimalFormat formato = new DecimalFormat("#,##0.00");
            System.out.println(consultaSQL);
            return "$ " + formato.format(importe);

        } catch (SQLException ex) {
            Logger.getLogger(TablaIU.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        return "-1";
    }

    // Recorro todo mi resulset y devuelto todo mi importe
    private double procesarValoresImportes(ResultSet rs) throws SQLException {

        double acumulador = 0;
        while (rs.next()) {
            acumulador += Double.parseDouble(rs.getString(1).replace(",", "."));
        }
        return acumulador;
    }

    private void cargarFechas() {
        try {
            String consulta = "SELECT DISTINCT fechaDate FROM transaccion";
            ResultSet fechas = db.consulta(consulta);
            List<String> listaDeDatos = new ArrayList<>();

            int i = 1;
            while (fechas.next()) {
                FechaComboBox.addItem(fechas.getString(i));
            }

        } catch (SQLException ex) {

            Logger.getLogger(TablaIU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarImagenes() {
        String dirActual = System.getProperty("user.dir");
        ordLejago.setIcon(new javax.swing.ImageIcon(dirActual + "\\images\\ord.png"));
        ordImporte.setIcon(new javax.swing.ImageIcon(dirActual + "\\images\\ord.png"));
        ordCant.setIcon(new javax.swing.ImageIcon(dirActual + "\\images\\ord.png"));
        try {
            BufferedImage iconImage = ImageIO.read(new File(dirActual+"\\images\\transaccion.png"));
            
            // Establecer la imagen como ícono de la aplicación
            this.setIconImage(iconImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void configurarElemtosSwing() {
        SpinnerModel model = new SpinnerNumberModel(10, 1, 30, 1);
        jSpinner1.setModel(model);
        JFormattedTextField textField = ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
        textField.setEditable(false);

    }

    private void limpiarTotales() {
        totalDoc.setText("");
        totalImporte.setText("");
        totalDoc.setText("");
        totalLegajos.setText("");
        totalReg1.setText(obtenerTotalRegistro());

    }

    private boolean tablaVacia() {
        return jTable1.getModel().getRowCount() == 0;
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JCheckBox FechaCheck;
    javax.swing.JComboBox<String> FechaComboBox;
    javax.swing.JCheckBox conceptoCheck;
    javax.swing.JCheckBox conceptoDistintoCheck1;
    javax.swing.JTextField conceptoTextField;
    javax.swing.JCheckBox descripcionCheck;
    javax.swing.JTextField descripcionTextField;
    javax.swing.JTextField docField;
    javax.swing.JCheckBox documentoCheck;
    javax.swing.JCheckBox empresaCheck;
    javax.swing.JTextField empresajField;
    javax.swing.JButton exportarBtn;
    javax.swing.JCheckBox grupoCheck;
    javax.swing.JTextField grupojField1;
    javax.swing.JLabel jLabel10CD;
    javax.swing.JLabel jLabel13CD;
    javax.swing.JLabel jLabel14CD;
    javax.swing.JSpinner jSpinner1;
    javax.swing.JTable jTable1;
    javax.swing.JCheckBox legajoCheck;
    javax.swing.JTextField legajoField;
    javax.swing.JLabel ordCant;
    javax.swing.JLabel ordImporte;
    javax.swing.JLabel ordLejago;
    javax.swing.JLabel totalDoc;
    javax.swing.JLabel totalImporte;
    javax.swing.JLabel totalLegajos;
    javax.swing.JLabel totalReg1;
    // End of variables declaration//GEN-END:variables

    private void configTable() {
       // this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

}
